### PR TITLE
fix: trace prefix check in escrow/unescrow when TokenId is IBC-created

### PR DESCRIPTION
**Pull request by Farhad-Shabani**
## Description
Along with this PR, a few methods were added to reduce code duplications.  

______

### PR author checklist

- [X] Updated code comments and documentation (e.g., `docs/`).
- [X] Tagged *one* reviewer who will be the one responsible for shepherding this PR.

### CODE REVIEW

**Comment by rnbguy** [comment]
Looks good. But to confirm everything. Is the following table (from ADR01) correct to send `tokA` from `sovA` -> `sovB` -> `sovC` -> `sovB` -> `sovA`.

| source rollup | source channel |        allowed denom in `MsgTransfer`         |
| :-----------: | :------------: | :-------------------------------------------: |
|    `sovA`     |     `chAB`     |                    `tokA`                     |
|    `sovB`     |     `chBC`     | ~`ransfer/chBA/tokA`~, `minted_token_name_to_id[transfer/chBA/tokA]` |
|    `sovC`     |     `chCB`     |       `transfer/chCB/transer/chBA/tokA`       |
|    `sovB`     |     `chBA`     |             `transfer/chBA/tokA`              |


That is, `mint` and `burn` use ibc denom trace but `escrow` and `unescrow` use native token id.

**Comment by rnbguy** [comment]
I think the following will fail to unescrow on `recv_packet`. 

https://github.com/informalsystems/sovereign-ibc/blob/03a92457ec5cbd57eb4e768e321a0a758f430943/modules/sov-ibc-transfer/src/context.rs#L464-L480

`recv_packet` uses full ibc denom trace. so, we need to map it back to native token id.

**Comment by rnbguy** [comment]
This is my analysis of the consumer trait methods and their required denom types.

|  method  |         trigger         | denom type |              condition               |
| :------: | :---------------------: | :--------: | :----------------------------------: |
|  escrow  |  user (`MsgTransfer`)   |   native   | token can't be a returning IBC token |
|   burn   |  user (`MsgTransfer`)   |    ibc     |                  -                   |
| unescrow | relayer (`recv_packet`) |    ibc     |                  -                   |
|   mint   | relayer (`recv_packet`) |    ibc     |                  -                   |

**Comment by rnbguy** [comment]
I believe this assumes that `burn` method has a native token denom.  

https://github.com/informalsystems/sovereign-ibc/blob/03a92457ec5cbd57eb4e768e321a0a758f430943/modules/sov-ibc-transfer/src/context.rs#L292-L307

But in ibc-rs, this is only reachable if the denom has the `<port-id>/<channel-id>/` prefix (where `<port-id>` and `<channel-id>` specifically correspond to the current channel end).

**Comment by rnbguy** [comment]
hey, there is a problem because of ibc-rs. The escrow takes _native_ denom type - which doesn't get translated to ibc denom when `send_packet` is created at ibc-rs side.

**Review by rnbguy — APPROVED** [review]
LGTM :tada:

I updated the example scenario section on ADR01

**Comment by Farhad-Shabani** [comment]
Thank you, Rano. Greatly appreciate your detailed review. 
As a summary of our discussions for future reference:

- Your comment [here](https://github.com/informalsystems/sovereign-ibc/pull/136#discussion_r1560849873) regarding the incorrect rejection of IBC-created tokens in escrows/un-escrows is valid. The added check in this PR as well.

- The third row you mentioned [here](https://github.com/informalsystems/sovereign-ibc/pull/138#issuecomment-2051497571) is accurate: `sovC - chCB - transfer/chCB/{tokOnB(transer/chBA/tokA)}.`

- It's beneficial to expand the ICS-20 transfer APIs in ibc-rs, allowing ibc-rs to comprehend how to map IBC denom traces to on-chain denominations. In the case of Sovereign, it is represented by `TokenId`. Feel free to open an issue for this.

**Pull request merged**
