### PR TITLE
latest changes from sdk-wip

### PR DESCRIPTION
**Pull request by rnbguy**
Closes: #158 

Syncs until Sovereign-Labs/sovereign-sdk-wip@fc1552b44acddc2674a783cd11f301a8b79cc4f3

## Description

______

### PR author checklist

- [ ] Linked to GitHub issue.
- [ ] Added tests.
- [ ] Updated code comments and documentation (e.g., `docs/`).
- [ ] Tagged *one* reviewer who will be the one responsible for shepherding this PR.

### CODE REVIEW

**Comment by rnbguy** [comment]
Currently stuck because our test setup uses async runtimes - which requires the `MockRollup` to be `Sync`. But Sovereign-Labs/sovereign-sdk-wip#694 introduced [`Credentials`](https://github.com/Sovereign-Labs/sovereign-sdk-wip/blob/913eb31f60ebbce8588de45ca57c9a1cc61d6004/module-system/sov-modules-api/src/transaction.rs#L284) which has a non-`Send` field.

**Comment by rnbguy** [comment]
I managed to compile the code, but the tests are failing. Possibly, the mock chains are not initialized with a proper genesis state.

**Comment by rnbguy** [comment]
Managed to get the tests passed. Sovereign-Labs/sovereign-sdk-wip#613 made `ProverStorage` immutable now. Needed `SimpleStorageManager` to persist changes between batches.

**Comment by rnbguy** [comment]
The only thing is remaining is the cw-check. It is failing with a nix error.

@soareschen, @ljoss17 any idea how I fix the nix error?

**Comment by soareschen** [comment]
> The only thing is remaining is the cw-check. It is failing with a nix error.
> 
> @soareschen, @ljoss17 any idea how I fix the nix error? You can locally reproduce the error by:
> 
> ```shell
> nix build .#sov-celestia-cw
> ```

The Cargo.lock file and the git dependency hash needs to be updated, which you can see from the error log. I have pushed the fix.

**Comment by rnbguy** [comment]
Thanks so much ! I am still onboarding to nix, so I was confused with the error.

So, the `Cargo.lock` file needs to stay in sync. I shouldn't update it to the latest crate versions. Gotcha !

**Pull request merged**
